### PR TITLE
fix: compilation issue for getting the process name

### LINKED ISSUE #162: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
when trying to install with 
```
git clone 'https://github.com/datadog/dd-trace-cpp'
cd dd-trace-cpp
cmake -B build .
cmake --build build -j
```

`cmake --build build -j` _throws cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'_ 
here _dd-trace-cpp/src/datadog/platform_util.cpp:194:9_

### PR DESCRIPTION
**Pull request by dmehala**
# Description

Resolves #162

### CODE REVIEW

File: src/datadog/platform_util.cpp [hunk 1]
```diff
@@ -98,7 +98,7 @@ std::tuple<std::string, std::string> get_windows_info() {
   // application manifest, which is the lowest version supported by the
   // application. Use `RtlGetVersion` to obtain the accurate OS version
   // regardless of the manifest.
-  using RtlGetVersion = auto(*)(LPOSVERSIONINFOEXW)->NTSTATUS;
+  using RtlGetVersion = auto (*)(LPOSVERSIONINFOEXW)->NTSTATUS;
```
Comment (dmehala) [inline src/datadog/platform_util.cpp:101]:
```suggestion
  using RtlGetVersion = auto(*)(LPOSVERSIONINFOEXW)->NTSTATUS;
```

**Review by zacharycmontoya — APPROVED** [review]
